ARG GOLANG_VERSION
ARG ALPINE_VERSION
FROM golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}
# install apps
RUN apk --no-cache --virtual .build-deps add tar make git gcc musl-dev binutils-gold
# Copy whole project
COPY . /app
# Set work dir
WORKDIR /app/extra
# Create kraken bin
RUN make kraken
# Create plugins
RUN make plugin